### PR TITLE
Sync contacts

### PR DESCRIPTION
**Pull request by as2388**
Review #49 first.

Adds a script for synchronising contacts between Rapid Pro instances. Adapted from the migrate_contacts.py script added in #49.

Still needs:
 - to be Dockerised
 - to run incrementally
before it is production ready.

### CODE REVIEW

**Comment by as2388** [comment]
Trying to merge without knowing what changed when is really starting to bother me.

I wonder if it might be better to keep a cache of what's on Rapid Pro and diff against that to compute what's changed before updating...?

**Comment by lukechurch** [comment]
Sorry @as2388 this got lost in the backlog. I wonder if another option might be to build a 'dry-run' option that just lists the changes that the tool is going to perform?

**Comment by lukechurch** [comment]
@as2388 any thought as to whether a dry run option would address your concerns?

**Comment by as2388** [comment]
> @as2388 any thought as to whether a dry run option would address your concerns?

Not the one raised earlier in this PR. All that would do is preview the changes that would be made, my question was about the data available when deciding what changes to make in the first place.

**Comment by as2388** [comment]
@lukechurch I changed the implementation to overwrite with the most recent flag if --force is passed, otherwise warn that they are different, as discussed. Please could you review now? 
Dockerising and incremental updates to come in a future PR.

**Pull request merged**
